export const dataCyAttribute = {
  createMeetup: 'createMeetup',
  login: 'login',
  submitLogin: 'submitLogin',
  meetupTitle: 'meetupTitle',
  buttonNext: 'buttonNext',
  buttonFinish: 'buttonFinish',
  news: 'news',
  createNews: 'createNews',
  submitNews: 'submitNews',
  supportButton: 'supportButton',
  logoutTooltip: 'logoutTooltip',
  tooltipWrapper: 'tooltipWrapper',
  imageSelector: 'imageSelector',
};
